language: go
jobs:
  include:
    - go: 1.12.x
    - go: tip
  allow_failures:
    - go: tip
os: linux
dist: xenial
before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
install:
  - dep ensure -v -vendor-only
  - go build ./...
script: true
after_script:
  - go test -race -v ./...
